org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1024m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# systemProp.http.proxyHost=myhost.com
# systemProp.http.proxyPort=12334
# systemProp.socksProxyHost=myhost.com
# systemProp.socksProxyPort=12334